export const skills = [
  { name: 'Python', type: 'backend' },
  { name: 'Java', type: 'backend' },
  { name: 'PHP', type: 'backend' },
  { name: 'SQL', type: 'backend' },
  { name: 'C++', type: 'backend' },
  { name: 'VB.NET', type: 'backend' },
  { name: 'React', type: 'frontend' },
  { name: 'React Native', type: 'frontend' },
  { name: 'Django', type: 'backend' },
  { name: 'HTML5', type: 'frontend' },
  { name: 'CSS', type: 'frontend' },
  { name: 'Bootstrap', type: 'frontend' },
  { name: 'PostgreSQL', type: 'backend' },
  { name: 'MySQL', type: 'backend' },
  { name: 'Microsoft Azure Services', type: 'cloud' },
  { name: 'AWS Services', type: 'cloud' },
  { name: 'Troubleshooting', type: 'soft' },
  { name: 'Data Analysis', type: 'soft' },
  { name: 'Responsive Design', type: 'frontend' },
  { name: 'Cloud Deployment', type: 'cloud' },
  { name: 'TinyML', type: 'cloud' },
];
